<?php

$approaches = [
    [
        'name' => 'Fernando Pedrosa',
        'mentor' => 'Dc. Antônio Maia',
        'student1' => 'Pb. Gabriel Ferreira',
        'student2' => 'Maria José',
        'typeContact' => 3,
        'totExplained' => 1,
        'totPeople' => 10,
        'totDecision' => 5,
        'totInteresting' => 3,
        'totReject' => 1,
        'totChristian' => 1,
        'meansGrowth' => true,
        'folowship' => 9,
    ],
    [
        'name' => 'João Batista',
        'mentor' => 'Dc. Antônio Maia',
        'student1' => 'Pb. Gabriel Ferreira',
        'student2' => 'Maria José',
        'typeContact' => 3,
        'totExplained' => 1,
        'totPeople' => 10,
        'totDecision' => 5,
        'totInteresting' => 3,
        'totReject' => 1,
        'totChristian' => 1,
        'meansGrowth' => true,
        'folowship' => 9,
    ],
    [
        'name' => 'Fernando Galego',
        'mentor' => 'Dc. Antônio Maia',
        'student1' => 'Pb. Gabriel Ferreira',
        'student2' => 'Maria José',
        'typeContact' => 3,
        'totExplained' => 1,
        'totPeople' => 10,
        'totDecision' => 5,
        'totInteresting' => 3,
        'totReject' => 1,
        'totChristian' => 1,
        'meansGrowth' => true,
        'folowship' => 9,
    ],
    [
        'name' => 'Thomas Ropkings',
        'mentor' => 'Dc. Antônio Maia',
        'student1' => 'Pb. Gabriel Ferreira',
        'student2' => 'Maria José',
        'typeContact' => 3,
        'totExplained' => 1,
        'totPeople' => 10,
        'totDecision' => 5,
        'totInteresting' => 3,
        'totReject' => 1,
        'totChristian' => 1,
        'meansGrowth' => true,
        'folowship' => 9,
    ],
    [
        'name' => 'Willian Tyndale',
        'mentor' => 'Dc. Antônio Maia',
        'student1' => 'Pb. Gabriel Ferreira',
        'student2' => 'Maria José',
        'typeContact' => 3,
        'totExplained' => 1,
        'totPeople' => 10,
        'totDecision' => 5,
        'totInteresting' => 3,
        'totReject' => 1,
        'totChristian' => 1,
        'meansGrowth' => true,
        'folowship' => 9,
    ],
];
